# Generated by Django 4.2.2 on 2023-06-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_alter_phone_id_alter_phone_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
